In [40]:
list = [23245, 27, 546, 215, -1234]

In [41]:
list

[23245, 27, 546, 215, -1234]

In [42]:
import numpy as np

In [43]:
a = np.array(list)

In [44]:
a

array([23245,    27,   546,   215, -1234])

In [45]:
# Cannot combine different data types in arrays (unlike with lists)

In [46]:
b = np.array([12, 455, 63.3, True, 'abc'])

In [47]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [48]:
# All elements in the array have been converted to strings.

In [49]:
list.pop()

-1234

In [50]:
list

[23245, 27, 546, 215]

In [51]:
a.mean()

4559.8

In [52]:
c = np.array([12, 455, 63.3, True])

In [53]:
c

array([ 12. , 455. ,  63.3,   1. ])

In [54]:
d = np.array([12, 455, 63, True])

In [55]:
d

array([ 12, 455,  63,   1])

In [56]:
e = np.array([False, False, 12, True])

In [57]:
e

array([ 0,  0, 12,  1])

In [58]:
f = np.array(['12', 15, 'abc', 19.5, False])

In [59]:
f

array(['12', '15', 'abc', '19.5', 'False'], dtype='<U32')

In [60]:
f.mean()

TypeError: cannot perform reduce with flexible type

In [61]:
list

[23245, 27, 546, 215]

In [62]:
list.insert(1, 55)

In [63]:
list

[23245, 55, 27, 546, 215]

---

In [64]:
# Slicing Lists

In [65]:
list

[23245, 55, 27, 546, 215]

In [66]:
list[1:]

[55, 27, 546, 215]

In [67]:
list[::2]

[23245, 27, 215]

In [68]:
list[0:2]

[23245, 55]

---

In [70]:
# Slicing Arrays

In [71]:
a

array([23245,    27,   546,   215, -1234])

In [72]:
a[2:]

array([  546,   215, -1234])

In [73]:
a[2:4]

array([546, 215])

In [74]:
a

array([23245,    27,   546,   215, -1234])

In [0]:
#Assigning an array or array slice to another variable passes a reference to the orginal array (unlike with lists, where assignment is a copy)

In [75]:
b = a[2:4]

In [76]:
b

array([546, 215])

In [77]:
b[0]

546

In [78]:
b[:] = 111

In [79]:
b

array([111, 111])

In [80]:
a

array([23245,    27,   111,   111, -1234])

In [87]:
list

[23245, 55, 27, 546, 215]

In [88]:
list1 = list[0:2]

In [89]:
list1

[23245, 55]

In [90]:
list1[1] = 2

In [91]:
list1

[23245, 2]

In [92]:
list

[23245, 55, 27, 546, 215]

In [81]:
#copy() is the method which copies an array.

In [82]:
c = a.copy()

In [83]:
c

array([23245,    27,   111,   111, -1234])

In [84]:
c[0] = 0

In [85]:
c

array([    0,    27,   111,   111, -1234])

In [86]:
a

array([23245,    27,   111,   111, -1234])